---
Name: silverware-staff
---

# Configure Content Controller:

SilverStripe\CMS\Controllers\ContentController:
  required_js:
    - "silverware/staff: client/dist/js/bundle.js"
  required_css:
    - "silverware/staff: client/dist/styles/bundle.css"

# Configure Admin Requirements:

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - "silverware/staff: admin/client/dist/styles/bundle.css"
  extra_requirements_javascript:
    - "silverware/staff: admin/client/dist/js/bundle.js"
